name: Playwright CI

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  playwright:
    uses: testingwithekki/ci-platform/.github/workflows/playwright.yml@main
    with:
      team: profile
